import { applyExpense, applyInvoice, applyVoucher } from "./accounting";
import type {
  AppData,
  Customer,
  Expense,
  InventoryItem,
  Invoice,
  Supplier,
  Voucher,
} from "./types";
import { DEFAULT_SETTINGS, EMPTY_DATA } from "./types";
import { daysAgoIso, todayIso } from "./utils";

function customer(
  id: string,
  name: string,
  phone: string,
  address: string,
  type: Customer["type"],
  createdAt: string,
): Customer {
  return { id, name, phone, address, balance: 0, type, createdAt };
}

function supplier(
  id: string,
  name: string,
  company: string,
  phone: string,
  createdAt: string,
): Supplier {
  return { id, name, company, phone, balance: 0, createdAt };
}

function item(
  partial: Omit<InventoryItem, "lastUpdated"> & { lastUpdated?: string },
): InventoryItem {
  return { lastUpdated: daysAgoIso(2), ...partial };
}

export function makeSeed(): AppData {
  const t = todayIso();
  let state: AppData = {
    ...EMPTY_DATA,
    settings: DEFAULT_SETTINGS,
    customers: [
      customer("c1", "خياطة النور", "777111222", "حي شميلة — صنعاء", "wholesale", daysAgoIso(80)),
      customer("c2", "مشغل الهدى", "733445566", "شارع حدة", "wholesale", daysAgoIso(60)),
      customer("c3", "أم محمد العلفي", "770998877", "حي السنينة", "retail", daysAgoIso(40)),
      customer("c4", "محل الأناقة", "711223344", "التذكرة — صنعاء", "wholesale", daysAgoIso(30)),
      customer("c5", "ورشة صنعاء الذهبية", "774556677", "الستين الشمالي", "wholesale", daysAgoIso(90)),
      customer("c6", "فاطمة علي", "735112233", "حي الصافية", "retail", daysAgoIso(12)),
    ],
    suppliers: [
      supplier("s1", "شركة الأقمشة المتحدة", "الأقمشة المتحدة", "777000111", daysAgoIso(100)),
      supplier("s2", "مستورد خيوط صنعاء", "خيوط صنعاء", "733000222", daysAgoIso(70)),
      supplier("s3", "معارض الإكسسوارات", "بيت الإكسسوار", "770000333", daysAgoIso(50)),
    ],
    inventory: [
      item({
        id: "i1",
        code: "FAB-101",
        name: "قماش قطن مصري",
        category: "fabric",
        unit: "roll",
        quantity: 46,
        costPrice: 18000,
        sellingPrice: 25000,
        minQuantity: 10,
        color: "أبيض",
      }),
      item({
        id: "i2",
        code: "FAB-204",
        name: "قماش شيفون ناعم",
        category: "fabric",
        unit: "roll",
        quantity: 8,
        costPrice: 22000,
        sellingPrice: 32000,
        minQuantity: 12,
        color: "وردي",
      }),
      item({
        id: "i3",
        code: "FAB-310",
        name: "قماش حرير أسود",
        category: "fabric",
        unit: "roll",
        quantity: 22,
        costPrice: 35000,
        sellingPrice: 48000,
        minQuantity: 6,
        color: "أسود",
      }),
      item({
        id: "i4",
        code: "FAB-418",
        name: "قماش كريب زيتي",
        category: "fabric",
        unit: "roll",
        quantity: 18,
        costPrice: 16000,
        sellingPrice: 23000,
        minQuantity: 8,
        color: "زيتي",
      }),
      item({
        id: "i5",
        code: "THR-01",
        name: "خيط تطريز ذهبي",
        category: "thread",
        unit: "kg",
        quantity: 4,
        costPrice: 9000,
        sellingPrice: 14000,
        minQuantity: 6,
        color: "ذهبي",
      }),
      item({
        id: "i6",
        code: "THR-02",
        name: "خيط تطريز أبيض",
        category: "thread",
        unit: "kg",
        quantity: 15,
        costPrice: 6500,
        sellingPrice: 11000,
        minQuantity: 5,
        color: "أبيض",
      }),
      item({
        id: "i7",
        code: "ACC-11",
        name: "أزرار لؤلؤ",
        category: "accessory",
        unit: "piece",
        quantity: 240,
        costPrice: 80,
        sellingPrice: 150,
        minQuantity: 50,
        color: "لؤلؤي",
      }),
      item({
        id: "i8",
        code: "ACC-22",
        name: "سحّاب معدني",
        category: "accessory",
        unit: "piece",
        quantity: 90,
        costPrice: 200,
        sellingPrice: 350,
        minQuantity: 30,
        color: "فضي",
      }),
      item({
        id: "i9",
        code: "MCH-03",
        name: "إبرة تطريز إلكترونية",
        category: "machine_part",
        unit: "piece",
        quantity: 3,
        costPrice: 4500,
        sellingPrice: 7000,
        minQuantity: 4,
        color: "—",
      }),
      item({
        id: "i10",
        code: "FAB-520",
        name: "قماش دانتيل",
        category: "fabric",
        unit: "meter",
        quantity: 64,
        costPrice: 1200,
        sellingPrice: 2200,
        minQuantity: 20,
        color: "بيج",
      }),
    ],
  };

  const invoices: Invoice[] = [
    {
      id: "inv1",
      invoiceNumber: "INV-0001",
      type: "sale",
      paymentType: "partial",
      invoiceType: "PRODUCT_SALE",
      partyId: "c1",
      date: daysAgoIso(2),
      items: [
        {
          id: "l1",
          inventoryItemId: "i1",
          name: "قماش قطن مصري",
          quantity: 6,
          unit: "طاقة / رول",
          unitPrice: 25000,
          total: 150000,
        },
        {
          id: "l2",
          inventoryItemId: "i6",
          name: "خيط تطريز أبيض",
          quantity: 2,
          unit: "كجم",
          unitPrice: 11000,
          total: 22000,
        },
      ],
      subTotal: 172000,
      discount: 2000,
      total: 170000,
      paidAmount: 70000,
      remainingAmount: 100000,
      status: "partial",
      isApproved: true,
      createdAt: daysAgoIso(2),
    },
    {
      id: "inv2",
      invoiceNumber: "INV-0002",
      type: "sale",
      paymentType: "deferred",
      invoiceType: "PRODUCT_SALE",
      partyId: "c5",
      date: daysAgoIso(1),
      items: [
        {
          id: "l3",
          inventoryItemId: "i3",
          name: "قماش حرير أسود",
          quantity: 5,
          unit: "طاقة / رول",
          unitPrice: 48000,
          total: 240000,
        },
        {
          id: "l4",
          inventoryItemId: "i10",
          name: "قماش دانتيل",
          quantity: 20,
          unit: "متر",
          unitPrice: 2200,
          total: 44000,
        },
      ],
      subTotal: 284000,
      discount: 4000,
      total: 280000,
      paidAmount: 0,
      remainingAmount: 280000,
      status: "unpaid",
      isApproved: true,
      createdAt: daysAgoIso(1),
    },
    {
      id: "inv3",
      invoiceNumber: "INV-0003",
      type: "sale",
      paymentType: "cash",
      invoiceType: "SERVICE",
      partyId: "c3",
      date: daysAgoIso(7),
      items: [
        {
          id: "l5",
          inventoryItemId: "SERVICE",
          name: "تطريز ثوب عرائس",
          description: "تطريز إلكتروني ذهبي على صدر وكمّين",
          quantity: 1,
          unit: "قطعة",
          unitPrice: 45000,
          total: 45000,
        },
      ],
      subTotal: 45000,
      discount: 0,
      total: 45000,
      paidAmount: 45000,
      remainingAmount: 0,
      status: "paid",
      isApproved: true,
      createdAt: daysAgoIso(7),
    },
    {
      id: "inv4",
      invoiceNumber: "INV-0004",
      type: "sale",
      paymentType: "partial",
      invoiceType: "SERVICE",
      partyId: "c2",
      date: daysAgoIso(4),
      items: [
        {
          id: "l6",
          inventoryItemId: "SERVICE",
          name: "تطريز شعار محلات",
          description: "شعار على 40 ثوب عمل",
          quantity: 40,
          unit: "قطعة",
          unitPrice: 1800,
          total: 72000,
        },
      ],
      subTotal: 72000,
      discount: 2000,
      total: 70000,
      paidAmount: 30000,
      remainingAmount: 40000,
      status: "partial",
      isApproved: true,
      createdAt: daysAgoIso(4),
    },
    {
      id: "inv5",
      invoiceNumber: "INV-0005",
      type: "sale",
      paymentType: "cash",
      invoiceType: "PRODUCT_SALE",
      partyId: "c4",
      date: t,
      items: [
        {
          id: "l7",
          inventoryItemId: "i4",
          name: "قماش كريب زيتي",
          quantity: 3,
          unit: "طاقة / رول",
          unitPrice: 23000,
          total: 69000,
        },
        {
          id: "l8",
          inventoryItemId: "i7",
          name: "أزرار لؤلؤ",
          quantity: 40,
          unit: "قطعة",
          unitPrice: 150,
          total: 6000,
        },
      ],
      subTotal: 75000,
      discount: 0,
      total: 75000,
      paidAmount: 75000,
      remainingAmount: 0,
      status: "paid",
      isApproved: true,
      createdAt: t,
    },
    {
      id: "inv6",
      invoiceNumber: "INV-0006",
      type: "sale",
      paymentType: "deferred",
      invoiceType: "SERVICE",
      partyId: "c6",
      date: t,
      items: [
        {
          id: "l9",
          inventoryItemId: "SERVICE",
          name: "تطريز فستان سهرة",
          description: "تطريز ورود على الذيل",
          quantity: 1,
          unit: "قطعة",
          unitPrice: 28000,
          total: 28000,
        },
      ],
      subTotal: 28000,
      discount: 0,
      total: 28000,
      paidAmount: 0,
      remainingAmount: 28000,
      status: "unpaid",
      isApproved: true,
      notes: "التسليم بعد أسبوع",
      createdAt: t,
    },
    {
      id: "pur1",
      invoiceNumber: "PUR-0001",
      type: "purchase",
      paymentType: "partial",
      partyId: "s1",
      date: daysAgoIso(20),
      items: [
        {
          id: "p1",
          inventoryItemId: "i1",
          name: "قماش قطن مصري",
          quantity: 20,
          unit: "طاقة / رول",
          unitPrice: 18000,
          total: 360000,
        },
        {
          id: "p2",
          inventoryItemId: "i2",
          name: "قماش شيفون ناعم",
          quantity: 10,
          unit: "طاقة / رول",
          unitPrice: 22000,
          total: 220000,
        },
      ],
      subTotal: 580000,
      discount: 10000,
      total: 570000,
      paidAmount: 400000,
      remainingAmount: 170000,
      status: "partial",
      isApproved: true,
      createdAt: daysAgoIso(20),
    },
    {
      id: "pur2",
      invoiceNumber: "PUR-0002",
      type: "purchase",
      paymentType: "cash",
      partyId: "s2",
      date: daysAgoIso(9),
      items: [
        {
          id: "p3",
          inventoryItemId: "i5",
          name: "خيط تطريز ذهبي",
          quantity: 8,
          unit: "كجم",
          unitPrice: 9000,
          total: 72000,
        },
      ],
      subTotal: 72000,
      discount: 0,
      total: 72000,
      paidAmount: 72000,
      remainingAmount: 0,
      status: "paid",
      isApproved: true,
      createdAt: daysAgoIso(9),
    },
  ];

  const vouchers: Voucher[] = [
    {
      id: "v0",
      voucherNumber: "DIR-0001",
      type: "receipt",
      partyType: "other",
      amount: 500000,
      date: daysAgoIso(28),
      paymentMethod: "cash",
      description: "رأس مال افتتاحي للصندوق",
      createdAt: daysAgoIso(28),
    },
    {
      id: "v1",
      voucherNumber: "REC-0001",
      type: "receipt",
      partyType: "customer",
      partyId: "c1",
      amount: 40000,
      date: daysAgoIso(10),
      paymentMethod: "cash",
      description: "دفعة من خياطة النور",
      createdAt: daysAgoIso(10),
    },
    {
      id: "v2",
      voucherNumber: "REC-0002",
      type: "receipt",
      partyType: "customer",
      partyId: "c5",
      amount: 80000,
      date: daysAgoIso(3),
      paymentMethod: "jeeb",
      description: "حوالة جيب — ورشة صنعاء الذهبية",
      createdAt: daysAgoIso(3),
    },
    {
      id: "v3",
      voucherNumber: "PAY-0001",
      type: "payment",
      partyType: "supplier",
      partyId: "s1",
      amount: 50000,
      date: daysAgoIso(6),
      paymentMethod: "remittance",
      description: "دفعة للمورد — الأقمشة المتحدة",
      createdAt: daysAgoIso(6),
    },
    {
      id: "v4",
      voucherNumber: "REC-0003",
      type: "receipt",
      partyType: "other",
      amount: 20000,
      date: daysAgoIso(2),
      paymentMethod: "cash",
      description: "إيداع رأس مال في الصندوق",
      createdAt: daysAgoIso(2),
    },
  ];

  const expenses: Expense[] = [
    {
      id: "e1",
      date: daysAgoIso(15),
      category: "إيجار",
      type: "work",
      description: "إيجار المعمل لشهر الحالي",
      amount: 80000,
      paymentMethod: "cash",
      createdAt: daysAgoIso(15),
    },
    {
      id: "e2",
      date: daysAgoIso(5),
      category: "كهرباء",
      type: "work",
      description: "فاتورة الكهرباء",
      amount: 18000,
      paymentMethod: "cash",
      createdAt: daysAgoIso(5),
    },
    {
      id: "e3",
      date: daysAgoIso(1),
      category: "رواتب",
      type: "work",
      description: "سلفة عامل التطريز",
      amount: 25000,
      paymentMethod: "cash",
      createdAt: daysAgoIso(1),
    },
  ];

  state = { ...state, invoices, vouchers, expenses };

  for (const inv of invoices) state = applyInvoice(state, inv, 1);
  for (const v of vouchers) state = applyVoucher(state, v, 1);
  for (const e of expenses) state = applyExpense(state, e, 1);

  return state;
}
