/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiRecoveryRouteImport } from './routes/api/recovery'
import { Route as SettingsAccessControlRouteImport } from './routes/settings.access-control'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexLazyRouteImport = createFileRoute('/')()
const CashboxLazyRouteImport = createFileRoute('/cashbox')()
const ExpensesLazyRouteImport = createFileRoute('/expenses')()
const InventoryLazyRouteImport = createFileRoute('/inventory')()
const PartiesLazyRouteImport = createFileRoute('/parties')()
const ReportsLazyRouteImport = createFileRoute('/reports')()
const SalesLazyRouteImport = createFileRoute('/sales')()
const VouchersLazyRouteImport = createFileRoute('/vouchers')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const CashboxLazyRoute = CashboxLazyRouteImport.update({
  id: '/cashbox',
  path: '/cashbox',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/cashbox.lazy').then((d) => d.Route))
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesLazyRoute = ExpensesLazyRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/expenses.lazy').then((d) => d.Route))
const InventoryLazyRoute = InventoryLazyRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/inventory.lazy').then((d) => d.Route))
const PartiesLazyRoute = PartiesLazyRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/parties.lazy').then((d) => d.Route))
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsLazyRoute = ReportsLazyRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/reports.lazy').then((d) => d.Route))
const SalesLazyRoute = SalesLazyRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sales.lazy').then((d) => d.Route))
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VouchersLazyRoute = VouchersLazyRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/vouchers.lazy').then((d) => d.Route))
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecoveryRoute = ApiRecoveryRouteImport.update({
  id: '/api/recovery',
  path: '/api/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccessControlRoute = SettingsAccessControlRouteImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/employees': typeof EmployeesRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/cashbox': typeof CashboxLazyRoute
  '/expenses': typeof ExpensesLazyRoute
  '/inventory': typeof InventoryLazyRoute
  '/parties': typeof PartiesLazyRoute
  '/reports': typeof ReportsLazyRoute
  '/sales': typeof SalesLazyRoute
  '/vouchers': typeof VouchersLazyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recovery': typeof ApiRecoveryRoute
  '/settings/access-control': typeof SettingsAccessControlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/employees': typeof EmployeesRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/cashbox': typeof CashboxLazyRoute
  '/expenses': typeof ExpensesLazyRoute
  '/inventory': typeof InventoryLazyRoute
  '/parties': typeof PartiesLazyRoute
  '/reports': typeof ReportsLazyRoute
  '/sales': typeof SalesLazyRoute
  '/vouchers': typeof VouchersLazyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recovery': typeof ApiRecoveryRoute
  '/settings/access-control': typeof SettingsAccessControlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/employees': typeof EmployeesRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRouteWithChildren
  '/cashbox': typeof CashboxLazyRoute
  '/expenses': typeof ExpensesLazyRoute
  '/inventory': typeof InventoryLazyRoute
  '/parties': typeof PartiesLazyRoute
  '/reports': typeof ReportsLazyRoute
  '/sales': typeof SalesLazyRoute
  '/vouchers': typeof VouchersLazyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/recovery': typeof ApiRecoveryRoute
  '/settings/access-control': typeof SettingsAccessControlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employees'
    | '/recovery'
    | '/settings'
    | '/cashbox'
    | '/expenses'
    | '/inventory'
    | '/parties'
    | '/reports'
    | '/sales'
    | '/vouchers'
    | '/api/health'
    | '/api/recovery'
    | '/settings/access-control'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employees'
    | '/recovery'
    | '/settings'
    | '/cashbox'
    | '/expenses'
    | '/inventory'
    | '/parties'
    | '/reports'
    | '/sales'
    | '/vouchers'
    | '/api/health'
    | '/api/recovery'
    | '/settings/access-control'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/employees'
    | '/recovery'
    | '/settings'
    | '/cashbox'
    | '/expenses'
    | '/inventory'
    | '/parties'
    | '/reports'
    | '/sales'
    | '/vouchers'
    | '/api/health'
    | '/api/recovery'
    | '/settings/access-control'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  EmployeesRoute: typeof EmployeesRoute
  RecoveryRoute: typeof RecoveryRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  CashboxLazyRoute: typeof CashboxLazyRoute
  ExpensesLazyRoute: typeof ExpensesLazyRoute
  InventoryLazyRoute: typeof InventoryLazyRoute
  PartiesLazyRoute: typeof PartiesLazyRoute
  ReportsLazyRoute: typeof ReportsLazyRoute
  SalesLazyRoute: typeof SalesLazyRoute
  VouchersLazyRoute: typeof VouchersLazyRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiRecoveryRoute: typeof ApiRecoveryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashbox': {
      id: '/cashbox'
      path: '/cashbox'
      fullPath: '/cashbox'
      preLoaderRoute: typeof CashboxLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recovery': {
      id: '/api/recovery'
      path: '/api/recovery'
      fullPath: '/api/recovery'
      preLoaderRoute: typeof ApiRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/access-control': {
      id: '/settings/access-control'
      path: '/access-control'
      fullPath: '/settings/access-control'
      preLoaderRoute: typeof SettingsAccessControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAccessControlRoute: typeof SettingsAccessControlRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccessControlRoute: SettingsAccessControlRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  EmployeesRoute: EmployeesRoute,
  RecoveryRoute: RecoveryRoute,
  SettingsRoute: SettingsRouteWithChildren,
  CashboxLazyRoute: CashboxLazyRoute,
  ExpensesLazyRoute: ExpensesLazyRoute,
  InventoryLazyRoute: InventoryLazyRoute,
  PartiesLazyRoute: PartiesLazyRoute,
  ReportsLazyRoute: ReportsLazyRoute,
  SalesLazyRoute: SalesLazyRoute,
  VouchersLazyRoute: VouchersLazyRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiRecoveryRoute: ApiRecoveryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
