/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CashboxRouteImport } from './routes/cashbox'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VouchersRouteImport } from './routes/vouchers'
import { Route as ApiRecoveryRouteImport } from './routes/api/recovery'
import { Route as SettingsAccessControlRouteImport } from './routes/settings.access-control'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashboxRoute = CashboxRouteImport.update({
  id: '/cashbox',
  path: '/cashbox',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VouchersRoute = VouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecoveryRoute = ApiRecoveryRouteImport.update({
  id: '/api/recovery',
  path: '/api/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccessControlRoute = SettingsAccessControlRouteImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => SettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cashbox': typeof CashboxRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/parties': typeof PartiesRoute
  '/recovery': typeof RecoveryRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/vouchers': typeof VouchersRoute
  '/api/recovery': typeof ApiRecoveryRoute
  '/settings/access-control': typeof SettingsAccessControlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cashbox': typeof CashboxRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/parties': typeof PartiesRoute
  '/recovery': typeof RecoveryRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/vouchers': typeof VouchersRoute
  '/api/recovery': typeof ApiRecoveryRoute
  '/settings/access-control': typeof SettingsAccessControlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cashbox': typeof CashboxRoute
  '/employees': typeof EmployeesRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/parties': typeof PartiesRoute
  '/recovery': typeof RecoveryRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/vouchers': typeof VouchersRoute
  '/api/recovery': typeof ApiRecoveryRoute
  '/settings/access-control': typeof SettingsAccessControlRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cashbox'
    | '/employees'
    | '/expenses'
    | '/inventory'
    | '/parties'
    | '/recovery'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/vouchers'
    | '/api/recovery'
    | '/settings/access-control'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cashbox'
    | '/employees'
    | '/expenses'
    | '/inventory'
    | '/parties'
    | '/recovery'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/vouchers'
    | '/api/recovery'
    | '/settings/access-control'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/cashbox'
    | '/employees'
    | '/expenses'
    | '/inventory'
    | '/parties'
    | '/recovery'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/vouchers'
    | '/api/recovery'
    | '/settings/access-control'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashboxRoute: typeof CashboxRoute
  EmployeesRoute: typeof EmployeesRoute
  ExpensesRoute: typeof ExpensesRoute
  InventoryRoute: typeof InventoryRoute
  PartiesRoute: typeof PartiesRoute
  RecoveryRoute: typeof RecoveryRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  VouchersRoute: typeof VouchersRoute
  ApiRecoveryRoute: typeof ApiRecoveryRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashbox': {
      id: '/cashbox'
      path: '/cashbox'
      fullPath: '/cashbox'
      preLoaderRoute: typeof CashboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vouchers': {
      id: '/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof VouchersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recovery': {
      id: '/api/recovery'
      path: '/api/recovery'
      fullPath: '/api/recovery'
      preLoaderRoute: typeof ApiRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/access-control': {
      id: '/settings/access-control'
      path: '/access-control'
      fullPath: '/settings/access-control'
      preLoaderRoute: typeof SettingsAccessControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsAccessControlRoute: typeof SettingsAccessControlRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccessControlRoute: SettingsAccessControlRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashboxRoute: CashboxRoute,
  EmployeesRoute: EmployeesRoute,
  ExpensesRoute: ExpensesRoute,
  InventoryRoute: InventoryRoute,
  PartiesRoute: PartiesRoute,
  RecoveryRoute: RecoveryRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  VouchersRoute: VouchersRoute,
  ApiRecoveryRoute: ApiRecoveryRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
